[package]
name = "changelog-gen"
version = "0.1.0"
authors = ["hindenbug <manoj.mk27@gmail.com>", "Vanshdeep Singh <kansi13@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
semver = "0.9.0"
git2 = "0.10.1"
